runtime: python39  # Ensure this matches the Python version you're using

entrypoint: gunicorn -b :$PORT app:app  # Specifies the command to start your application

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto
